[package]
name = "simple-pass-gen"
version = "0.1.7"
edition = "2021"
authors = ["Andrei Dodu"]
license = "MIT"
description = "Simple-Pass-Gen is a password generator library."

[dependencies]
rand = "0.8.5"
